### PR TITLE
fix: delete deletable tilesets and tiles when deleting style

### LINKED ISSUE #3: Add delete route for styles
`DELETE /tilesets/:id` to delete a tileset (should clear all local storage)

Qn: What about clearing storage (downloaded / cached tiles) without actually deleting the tileset? I think we might need that.

### PR DESCRIPTION
**Pull request by achou11**
Fixes #3 

potentially running into an issue with the statements that I use to delete the tilesets. see https://github.com/WiseLibs/better-sqlite3/issues/842 for details

### CODE REVIEW

File: src/api.ts [hunk 1]
```diff
@@ -954,14 +954,53 @@ function createApi({
...
+            SELECT SourceToTilesetIdOuter.value AS tilesetId, Style.id AS styleId
+            FROM Style, json_each(Style.sourceIdToTilesetId, '$') AS SourceToTilesetIdOuter
+            JOIN (
+              SELECT SourceToTilesetIdInner.value AS tilesetId, COUNT(SourceToTilesetIdInner.value) AS freq
+              FROM Style, json_each(Style.sourceIdToTilesetId, '$') AS SourceToTilesetIdInner
+              GROUP BY SourceToTilesetIdInner.value
+            ) AS TilesetIdFreq ON SourceToTilesetIdOuter.value = TilesetIdFreq.tilesetId
+            WHERE freq = 1;
+          `
+        ).run()
```
Comment (achou11) [inline src/api.ts:983]: have no idea if there's a best practice around using views 🤷 

also, view statements can't take params, which would've made this + the following statements a little less verbose

File: src/api.ts [hunk 2]
```diff
@@ -954,14 +954,53 @@ function createApi({
...
       }
 
-      // TODO
-      // - Delete any orphaned tilesets and sprites
-      // - How to handle glpyhs here?
+      // TODO: How to handle glpyhs here?
       const deleteStyleTransaction = db.transaction(() => {
         db.prepare(
           'DELETE FROM Import WHERE areaId IN (SELECT id FROM OfflineArea WHERE styleId = ?)'
         ).run(id)
```
Comment (gmaclennan) [inline src/api.ts:961]: I don't think we want to delete anything from the import table? I guess we could, but it's fine I think to keep that record in there.

**Review by gmaclennan — COMMENTED** [review]
Quick thoughts based on 5 mins looking at this. Do we already have / plan to add a deleteTileset function? Does it also delete all tiles that are part of that tileset? 
I think that rather than trying to do everything in a single transaction (which I know has the advantage of being atomic), we separate this out:

1. Query the tilesetIds that need to be deleted
2. Call api.deleteTileset() on each of those ids (also handles tiledata deletions?)
3. Delete the style and other resources (offline areas, sprites)

That will maybe make this more manageable? And avoid re-implementing logic in deleteTileset and deleteStyle.

**Comment by achou11** [comment]
yeah we already have something for that. not sure it deletes the tiles though at the moment. will look into it!

File: src/api.ts (hunk 2 above)
Comment (achou11) [reply src/api.ts:961]: what about the offline areas table? thought it would make sense to delete there, but in order to do that, we'd need to either delete the associated records in the import table, or update the import table to dereference the offline areas

**Comment by achou11** [comment]
> yeah we already have something for that. not sure it deletes the tiles though at the moment. will look into it!

was wrong about this, we don't have an implementation for deleting tilesets. something to work on!

File: src/api.ts (hunk 2 above)
Comment (gmaclennan) [reply src/api.ts:982]: Yes, good point, let's delete the imports too.

**Comment by gmaclennan** [comment]
I think this is good to go now.

**Review by gmaclennan — APPROVED** [review]
