### PR TITLE
fix: return proper responses for get tile endpoint

### LINKED ISSUE #57: Tile responses are incorrect in some cases
if an upstream tile request fails (either because there is no connectivity, the upstream is 404, or upstream is 500), we don't properly catch it, and it comes back as a 500 error. This is particularly relevant for offline scenarios - we want 404 errors, not a 500 error / uncaught error.

### PR DESCRIPTION
**Pull request by achou11**
Fixes #57 

Notes:
- Similar to the glyphs implementation, we need to forward and adjust certain responses we send based on the upstream request and internet connectivity. If a tile isn't found locally:
  - if upstream responds with 4XX, ~we forward the response~ respond with a 404
  - if upstream responds with 5XX, we respond with a 404
  - if there's no internet connectivity, we respond with a 404

### CODE REVIEW

File: src/api/tiles.ts [hunk 1]
```diff
@@ -170,18 +176,6 @@ function createTilesApi({
...
-        db.prepare<{
-          etag?: string
-          tilesetId: string
-          upstreamUrl?: string
-        }>(
-          'UPDATE Tileset SET (upstreamUrl) = (:upstreamUrl) WHERE id = :tilesetId'
-        ).run({
-          tilesetId,
-          upstreamUrl: upstreamTileUrl,
-        })
```
Comment (achou11) [inline src/api/tiles.ts:183]: pretty sure this would've caused some wild bugs - think at the time, i was confused about how upstream urls worked in the context of the tilejson spec 😅

**Comment by gmaclennan** [comment]
Hi @achou11, I haven't done a full review (currently on a flight), but my initial thought about this is way we are handling the mapbox access token.

As far as I know (worth double-checking in the Mapbox API docs and doing some test requests), when you request a Style or a TileJSON with an access token, then the tile template URL that is returned already has the access token included as part of the template URL. I don't think any code in the server needs to know about the access token: we just store the tile template URL (which may or may not include the access token) and then the rest of the code does not need to be concerned about it.

**Comment by achou11** [comment]
@gmaclennan boarding my flight now but did a quick test of fetching a style and the response doesn't seem to embed the access token in the template urls.

the reason for handling the access token is because the routes need to be able to handle the token since the mapbox client (whether from js, java, etc) will append the access token as part of the query string to whatever asset url is provided (the asset url usually will not have the access token from what I've seen)

**Comment by achou11** [comment]
> I don't think any code in the server needs to know about the access token: we just store the tile template URL (which may or may not include the access token) and then the rest of the code does not need to be concerned about it.

yeah that's correct. the only relevant handling of the access toke we need to do is append it to whatever template url we're using to make an upstream request. see previous comment for why we need to deal with an access token at all in the first place

**Comment by achou11** [comment]
Note to self: update the PRs so that we persist the access token when creating a style (POST /styles), so that the template urls will include that token already. this way we can support creating different mapbox styles that use different access tokens.

**Comment by achou11** [comment]
Follow up needed:

the GET tile endpoint should include information about the upstream error when a 4XX error occurs. The map server will return a 404 to the client in this case, but it's helpful for it to have access to the upstream error that results in that
